### ISSUE TITLE
Chapter 5: Helm Ingress Install Command Fails (out of date?)

### ISSUE THREAD

**Issue by archmangler** [PacktPublishing/Hands-On-Kubernetes-on-Azure#2]
The helm install command for nginx ingress installation fails:

```
traiano@Azure:~$ helm install nginx/ingress --set rbac.create=falseError: failed to download "nginx/ingress" (hint: running `helm repo update` may help)
```

- However the package manager has been updated with helm update ....

**Comment by gshiva** [comment]
Can you try

`helm install stable/nginx-ingress --set rbac.create=false`

Thanks

**Comment by devopsdymyr** [comment]
As per the instruction install but not solved ingress.
![Screenshot from 2019-08-11 22-48-15](https://user-images.githubusercontent.com/41105507/62837235-fbf29a80-bc8a-11e9-9231-4acbfbe07ec0.png)
![Screenshot from 2019-08-11 22-49-11](https://user-images.githubusercontent.com/41105507/62837241-090f8980-bc8b-11e9-9f42-48092668ef7e.png)
![Screenshot from 2019-08-11 22-50-41](https://user-images.githubusercontent.com/41105507/62837244-0c0a7a00-bc8b-11e9-8d4a-729d089caf6f.png)
![Screenshot from 2019-08-11 22-52-39](https://user-images.githubusercontent.com/41105507/62837245-0f056a80-bc8b-11e9-9132-8d1ed88069d2.png)

I am trying with as per steps provided in the book.let me know anything required to change in the chapter 5

**Comment by gshiva** [comment]
Can you also try this?

** the following doesn't set the rbac.create =false flag **

```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
helm install stable/nginx-ingress
```

#2 - might also need this update.
