### ISSUE TITLE
image microsoft/azure-vote-front is no longer valid 

### ISSUE THREAD

**Issue by emilbra** [PacktPublishing/Hands-On-Kubernetes-on-Azure#5]
Hi!
Seems the image microsoft/azure-vote-front as used in azure-vote.yaml in chapter 2 is no longer valid.

Tried using mcr.microsoft.com/azuredocs/azure-vote-front:v2 as image instead, and this seems to be correct. :D

**Comment by shruthis-shetty** [comment]
Hey @emilbra , I hope the issue got solved as of now. Please reply!!!
